version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - 'dist/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'
