version: 0.2
env:
  secrets-manager:
    DOCKERHUB_TOKEN: sit-cwa-sk:token
    DOCKERHUB_USER: sit-cwa-sk:user
phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t corporate-web-admin:latest .
  post_build:
    commands:
      - docker tag corporate-web-admin:latest ${DOCKERHUB_USER}/corporate-web-admin:latest
      - docker push ${DOCKERHUB_USER}/corporate-web-admin:latest