version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm test
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g typescript
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  name: CorporateWebAdminBuild-$(date +%Y-%m-%d)
