import { TCorporateData } from "@/pages/createJob/constant/type";
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

const initialState: TCorporateData = {
  registerId: "",
  Info: {
    id: "",
    createBy: "",
    CreatedAt: "",
    DeletedAt: null,
    registerId: "",
    name: "",
    registrationNo: "",
    taxId: "",
    dateOfIncorporation: "",
  },
  CorporateCountry: [],
  CorporateAddress: [],
  CorporateFinancials: {
    id: "",
    createBy: "",
    CreatedAt: "",
    DeletedAt: null,
    registerId: "",
    registeredCapital: 0,
    revenuePerYear: 0,
    netProfitLoss: 0,
    shareholderEquity: 0,
  },
  CorporateTypes: {
    CreatedAt: "",
    DeletedAt: null,
    id: "",
    createBy: "",
    registerId: "",
    isJuristicThailand: false,
    isTaxExempt: false,
    isNonTaxExempt: false,
    isJuristicForeign: false,
    isOperatingInThailand: false,
    isNonOperatingInThailand: false,
    isOther: false,
    isPartnership: false,
    isGovernmentStateEnterprise: false,
    isCoOperative: false,
    isTaxExemptCompany: false,
  },
  BusinessTypes: {
    createBy:"",
    CreatedAt: "",
    DeletedAt: null,
    id: "",
    registerId: "",
    isAntiqueTrading: false,
    isHotelRestaurant: false,
    isArmament: false,
    isInsuranceAssurance: false,
    isCasinoGambling: false,
    isJewelryGoldTrading: false,
    isFoundation: false,
    isPropertyRealEstate: false,
    isMoneyTransfer: false,
    isEmploymentAgency: false,
    isEntertainment: false,
    isTravel: false,
    isFinancial: false,
    isEducationCenter: false,
    isForeignCurrencyExchange: false,
    isCryptoRelated: false,
    isOtherBusiness: false,
    otherBusinessType: "",
  },
  SourceOfIncomes: {
    createBy:"",
    CreatedAt: "",
    DeletedAt: null,
    id: "",
    registerId: "",
    isDonation: false,
    isLoan: false,
    isOtherIncome: false,
    isRevenue: false,
    isRevenueSelling: false,
    isStock: false,
    otherIncome: "",
  },
  CountrySourceIncomes: [],
  Contact: null,
  Directors: null,
  AuthorizedPersons: null,
  IndividualShareholders: null,
  Juristics: [],
  Banks: [],
};

const editCorporateSlice = createSlice({
  name: "juristicType",
  initialState,
  reducers: {
    setCorporateData(state, action: PayloadAction<TCorporateData>) {
      return { ...state, ...action.payload };
    },
    clearCorporateData(state) {
      Object.assign(state, initialState);
    },
  },
});

export const { setCorporateData,clearCorporateData } = editCorporateSlice.actions;
export default editCorporateSlice.reducer;
